config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing'))
]

mailing/urls.py
from django.urls import path
from mailing.views import MailingRecipientListView, MailingRecipientDetailView, MailingRecipientCreateView, \
    MailingRecipientUpdateView, MailingRecipientDeleteView, MessageListView, MessageDetailView, MessageCreateView, \
    MessageUpdateView, MessageDeleteView
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path("recipient_list/", MailingRecipientListView.as_view(), name='recipient_list'),
    path("recipient/<int:pk>", MailingRecipientDetailView.as_view(), name='recipient_detail'),
    path("recipient/create/", MailingRecipientCreateView.as_view(), name='recipient_create'),
    path("recipient/<int:pk>/update/", MailingRecipientUpdateView.as_view(), name='recipient_update'),
    path("recipient/<int:pk>/delete/", MailingRecipientDeleteView.as_view(), name='recipient_delete'),

    path("message_list/", MessageListView.as_view(), name="message_list"),
    path("message/<int:pk>", MessageDetailView.as_view(), name="message_detail"),
    path("message/create", MessageCreateView.as_view(), name="message_create"),
    path("message/<int:pk>/update/", MessageUpdateView.as_view(), name="message_update"),
    path("message/<int:pk>/delete/", MessageDeleteView.as_view(), name="message_delete")
]

mailing/models.py
from django.db import models


class MailingRecipient(models.Model):
    """Класс получателя рассылки"""

    email = models.EmailField(
        unique=True, help_text="email получателя рассылки", verbose_name="email получателя рассылки"
    )
    full_name = models.CharField(max_length=150, verbose_name="Ф.И.О. получателя", help_text="Ф.И.О. получателя")
    commentary = models.TextField(verbose_name="Комментарий о получателе рассылки", blank=True, null=True)

    def __str__(self):
        """Строковое представление получателя"""
        return f"{self.full_name}"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["full_name"]


class Message(models.Model):
    """Класс объекта 'сообщение'"""

    subject = models.CharField(max_length=150, verbose_name="Тема сообщения", help_text="Тема")
    message = models.TextField(verbose_name="Тескт сообщения", help_text="Тескт сообщения")


class Mailing(models.Model):
    """Класс объекта 'рассылка'"""

    STATUS_CHOICES = [("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")]

    start_date = models.DateTimeField(verbose_name="Дата и время первой рассылки")
    end_date = models.DateTimeField(verbose_name="Дата и время окончания рассылки")
    status = models.CharField(
        max_length=9, verbose_name="Статус рассылки", blank=True, null=True, choices=STATUS_CHOICES, default="Создана"
    )
    message = models.ForeignKey(Message, verbose_name="сообщение", on_delete=models.CASCADE, related_name="mailings")
    recipients = models.ManyToManyField(
        MailingRecipient, verbose_name="Получатели рассылки", related_name="recipients"
    )

mailing/forms.py
from django.forms import ModelForm

from mailing.models import MailingRecipient, Message


class StyleForm:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingRecipientForm(StyleForm, ModelForm):
    class Meta:
        model = MailingRecipient
        fields = "__all__"


class MessageForm(StyleForm, ModelForm):
    class Meta:
        model = Message
        fields = "__all__"

mailing/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mailing.forms import MailingRecipientForm, MessageForm
from mailing.models import MailingRecipient, Message


class MailingRecipientListView(ListView):
    """Класс представления списка получателей"""
    model = MailingRecipient


class MailingRecipientDetailView(DetailView):
    """Класс детального представления одного получателя"""
    model = MailingRecipient


class MailingRecipientCreateView(CreateView):
    """Класс создания получателя"""
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailing:recipient_list")


class MailingRecipientUpdateView(UpdateView):
    """Класс изменения получателя"""
    model = MailingRecipient
    form_class = MailingRecipientForm
    success_url = reverse_lazy("mailing:recipient_list")


class MailingRecipientDeleteView(DeleteView):
    """Класс удаления получателя"""
    model = MailingRecipient
    success_url = reverse_lazy("mailing:recipient_list")


class MessageListView(ListView):
    """Класс представления сообщения"""
    model = Message


class MessageDetailView(DetailView):
    """Класс детального сообщения"""
    model = Message


class MessageCreateView(CreateView):
    """Класс создания сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class MessageUpdateView(UpdateView):
    """Класс изменения сообщения"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")


class MessageDeleteView(DeleteView):
    """Класс удаления сообщения"""
    model = Message
    success_url = reverse_lazy("mailing:message_list")

mailing/templates/mailing/mailingrecipient_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Создание клиента</h1>
    </div>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
            <p class="card-text">Действительно хотите удалить клиента: {{ object.full_name }}</p>
            <div class="card-boby mt-3">
                {% csrf_token %}
            </div>
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a type="button" class="btn btn-primary btn-sm border"
               href="{% url 'mailing:recipient_list' %}">Отменить
            </a>
        </div>
    </form>
</main>
{% endblock %}

mailing/templates/mailing/mailingrecipient_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Информация о клиенте</h1>
    </div>
    <div class="card">
        <div class="card-header">{{ object.email }}</div>
        <div class="card-body">
            <h5 class="card-title">{{ object.full_name }}</h5>
            <p class="card-text">{{ object.commentary | default:"Комментарий отсутствует" }}.</p>
            <a href="{% url 'mailing:recipient_update' object.id %}" class="btn btn-primary">Изменить данные</a>
            <a href="{% url 'mailing:recipient_delete' object.id %}" class="btn btn-danger">Удалить</a>
        </div>
        <a href="{% url 'mailing:recipient_list' %}" class="list-group-item list-group-item-action">
            <div class="card-footer text-muted">Вернуться к списку клиентов</div>
        </a>
    </div>
</main>

{% endblock %}

mailing/templates/mailing/mailingrecipient_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Создание клиента</h1>
    </div>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="container ms-6">
            <div class="row ms-5">
                <div class="col-5">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</main>
{% endblock %}

mailing/templates/mailing/mailingrecipient_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Список получателей рассылки</h1>
    </div>
    <ol class="list-group list-group-numbered">
        {% for recipient in object_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <a href="{% url 'mailing:recipient_detail' recipient.id %}" class="list-group-item list-group-item-action">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ recipient.email }}</div>
                    <div>{{ recipient.full_name }}</div>
                </div>
                <span class="badge bg-primary rounded-pill text-end">14</span>
            </a>
        </li>
        {% endfor %}
    </ol>
</main>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Удаление сообщения</h1>
    </div>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
            <p class="card-text">Действительно хотите удалить сообщение: {{ object.subject }}</p>
            <div class="card-boby mt-3">
                {% csrf_token %}
            </div>
            <button class="btn btn-danger" type="submit">Удалить</button>
            <a type="button" class="btn btn-primary btn-sm border"
               href="{% url 'mailing:message_list' %}">Отменить
            </a>
        </div>
    </form>
</main>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Сообщение</h1>
    </div>
    <div class="card">
        <div class="card-header">{{ object.subject }}</div>
        <div class="card-body">
            <p class="card-text">{{ object.message }}.</p>
            <a href="{% url 'mailing:message_update' object.id %}" class="btn btn-primary">Изменить данные</a>
            <a href="{% url 'mailing:message_delete' object.id %}" class="btn btn-danger">Удалить</a>
        </div>
        <a href="{% url 'mailing:message_list' %}" class="list-group-item list-group-item-action">
            <div class="card-footer text-muted">Вернуться к списку сообщений</div>
        </a>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Создание сообщения</h1>
    </div>
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="container ms-6">
            <div class="row ms-5">
                <div class="col-5">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</main>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Список сообщений для рассылки</h1>
    </div>
    <ol class="list-group list-group-numbered">
        {% for message in object_list %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <a href="{% url 'mailing:message_detail' message.id %}" class="list-group-item list-group-item-action">
                <div class="ms-2 me-auto">
                    <div class="fw-bold ">Тема сообщения: {{ message.subject }}</div>
                    <div>Текст сообщения: {{ message.message }}</div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ol>
</main>
{% endblock %}